
<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<h1>تمرین جامع عملی: آماده‌سازی آزمایشگاه برای بوت‌کمپ</h1>
<p><b>زمان پیشنهادی:</b> حدود ۳ ساعت</p>

<h2>سناریو</h2>
<p>
فردا قرار است یک <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">AI Bootcamp</span> برگزار شود.
شما مسئول آماده‌سازی سیستم کلاس هستید و باید قبل از شروع Bootcamp سه بخش عملی را بررسی کنید.
هدف این است که هر بخش را اجرا کنید، Output آن را ببینید و بتوانید دلیل نتیجه را توضیح دهید.
</p>

<table style="width:100%; border-collapse:collapse; margin:10px 0;">
<tr>
<th style="border:1px solid #aaa;padding:7px;text-align:right;">بخش</th>
<th style="border:1px solid #aaa;padding:7px;text-align:left;" dir="ltr">Technical Focus</th>
<th style="border:1px solid #aaa;padding:7px;text-align:right;">کاری که انجام می‌دهید</th>
</tr>
<tr>
<td style="border:1px solid #aaa;padding:7px;text-align:right;">بخش اول</td>
<td style="border:1px solid #aaa;padding:7px;text-align:left;" dir="ltr">Demo 1 — Pretrained NLP Model</td>
<td style="border:1px solid #aaa;padding:7px;text-align:right;">بررسی و اجرای یک مدل آماده برای <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Sentiment Classification</span></td>
</tr>
<tr>
<td style="border:1px solid #aaa;padding:7px;text-align:right;">بخش دوم</td>
<td style="border:1px solid #aaa;padding:7px;text-align:left;" dir="ltr">Demo 2 — Memory & Quantization</td>
<td style="border:1px solid #aaa;padding:7px;text-align:right;">تحلیل <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Memory</span> و <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Quantization</span> برای یک مدل فرضی <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">7B</span> روی سخت‌افزار محدود</td>
</tr>
<tr>
<td style="border:1px solid #aaa;padding:7px;text-align:right;">بخش سوم</td>
<td style="border:1px solid #aaa;padding:7px;text-align:left;" dir="ltr">Demo 3 — Semantic Search</td>
<td style="border:1px solid #aaa;padding:7px;text-align:right;">ساخت جست‌وجوی معنایی برای محتوای دوره</td>
</tr>
</table>

<p>
در پایان باید یک <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Jupyter Notebook</span> تحویل دهید که
<span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Code</span>، <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Output</span> و پاسخ کوتاه تحلیلی هر مأموریت در آن ثبت شده باشد.
</p>

<p><b>نکته مهم:</b></p>
<p>
در این تمرین فقط دو Model واقعی را Load می‌کنید:
<span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">DistilBERT</span> برای <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Classification</span> و
<span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">all-MiniLM-L6-v2</span> برای <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Embedding</span>.
</p>
<p>
مدل <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">7B</span> در بخش دوم فقط یک <b>مدل فرضی برای محاسبات آموزشی</b> است
و قرار نیست Download یا اجرا شود.
</p>
</div>


<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<h3>Bootcamp roadmap</h3>
<pre>
Demo 1
DistilBERT
→ Hugging Face inspection
→ Transformers pipeline
→ Tokenizer
→ Logits / Probabilities
→ Padding / Truncation

Demo 2
Hypothetical 7B model
→ Idealized raw weight-memory estimate
→ Quantization
→ Reconstruction error
→ Hardware-fit reasoning

Demo 3
Sentence Transformer
→ Sentence embeddings
→ Document embeddings
→ Semantic Search
→ TF-IDF comparison
→ Precision@3 / Recall@3
</pre>
</div>


<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<h2>قبل از شروع</h2>
<p>
برای اینکه زمان تمرین صرف آماده‌سازی محیط نشود، کتابخانه‌های موردنیاز باید از قبل نصب شده باشند.
فهرست دقیق در <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Cell</span> بعدی آمده است.
</p>
<p>
<b>نکته اجرایی:</b> بعضی از Code Cellها دارای <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">TODO</span> هستند.
این Cellها بخشی از سؤال تمرین‌اند و تا زمانی که TODOها را کامل نکنید نباید انتظار داشته باشید
<span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Run All</span> بدون توقف اجرا شود.
</p>
</div>


<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<pre>
torch
transformers
huggingface_hub
sentence-transformers
scikit-learn
numpy
pandas
</pre>
</div>


<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<p>
برای Load کردن Modelها، اتصال اینترنت یا Cache کامل Modelها کافی است.
</p>
<p>
اما در <b>مأموریت ۱</b> از <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">model_info()</span> و <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Model Card</span> استفاده می‌شود؛
بنابراین برای این بخش باید به <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Hugging Face Hub</span> دسترسی داشته باشید.
اگر کلاس قرار است کاملاً Offline باشد، مدرس باید Metadata و نسخه‌ای از Model Card را از قبل در اختیار دانشجوها قرار دهد.
</p>
<p>
در این نسخه از تمرین هیچ <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Local Runtime</span> یا سرویس جداگانه‌ای لازم نیست.
</p>
<h3>نمای کلی Modelها</h3>
</div>


<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<table style="width:100%; border-collapse:collapse;">
<tr>
<th style="border:1px solid #aaa; padding:7px; text-align:left;">Model / Object</th>
<th style="border:1px solid #aaa; padding:7px; text-align:left;">Role</th>
</tr>
<tr>
<td style="border:1px solid #aaa; padding:7px;">DistilBERT SST-2</td>
<td style="border:1px solid #aaa; padding:7px;">Sentiment Classification</td>
</tr>
<tr>
<td style="border:1px solid #aaa; padding:7px;">Hypothetical 7B model</td>
<td style="border:1px solid #aaa; padding:7px;">Memory / Quantization analysis only</td>
</tr>
<tr>
<td style="border:1px solid #aaa; padding:7px;">all-MiniLM-L6-v2</td>
<td style="border:1px solid #aaa; padding:7px;">Sentence Embedding / Retrieval</td>
</tr>
</table>
</div>

In [20]:
import numpy as np
import pandas as pd
import torch

from huggingface_hub import model_info
from transformers import (
    pipeline,
    AutoTokenizer,
    AutoModelForSequenceClassification,
)
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><h3>شناسه‌ها و فرض سخت‌افزار</h3><p>مقادیر <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Cell</span>‏ بعدی را در طول تمرین استفاده کنید.</p></div><div dir="ltr" style="direction:ltr; text-align:left; line-height:1.5; font-family:Arial, sans-serif; margin-top:4px; margin-bottom:12px;"><h4 style="margin-top:0;">Model IDs &amp; Hardware Assumption</h4></div>

In [21]:
SENTIMENT_MODEL_ID = (
    "distilbert/"
    "distilbert-base-uncased-finetuned-sst-2-english"
)

EMBEDDING_MODEL_ID = "sentence-transformers/all-MiniLM-L6-v2"

# Hardware assumption for the memory exercise.
GPU_VRAM_GIB = 8
SYSTEM_RAM_GIB = 32

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><h2>داده‌های بخش جست‌وجو</h2><p>در <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Demo 3</span>‏ از مجموعه‌ای شامل ۱۲ <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Document</span>‏ استفاده کنید. هر <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Document</span>‏ دارای چهار فیلد است: <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">id</span>‏، <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">title</span>‏، <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">category</span>‏ و <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">text</span>‏.</p></div><div dir="ltr" style="direction:ltr; text-align:left; line-height:1.5; font-family:Arial, sans-serif; margin-top:4px; margin-bottom:12px;"><h3 style="margin-top:0;">Semantic Search Data</h3></div>

In [22]:
documents = [
    {
        "id": "python-environment",
        "title": "Python virtual environments",
        "category": "setup",
        "text": "Create a virtual environment to isolate the packages used by a Python project.",
    },
    {
        "id": "git-submission",
        "title": "Project submission",
        "category": "workflow",
        "text": "Students should upload the completed project to the course GitHub repository before the deadline.",
    },
    {
        "id": "json-data",
        "title": "JSON data exchange",
        "category": "python",
        "text": "JSON is a common format for exchanging structured data between applications and APIs.",
    },
    {
        "id": "api-requests",
        "title": "Calling an API",
        "category": "python",
        "text": "The requests library sends HTTP requests and receives data from a web API.",
    },
    {
        "id": "linear-algebra",
        "title": "Vectors and matrices",
        "category": "machine-learning",
        "text": "Vectors and matrices provide the mathematical language for many machine learning operations.",
    },
    {
        "id": "model-evaluation",
        "title": "Model evaluation",
        "category": "machine-learning",
        "text": "Use a validation set and suitable metrics to estimate how a model behaves on unseen data.",
    },
    {
        "id": "cnn",
        "title": "Convolutional neural networks",
        "category": "deep-learning",
        "text": "CNNs learn visual patterns with convolutional filters and are widely used for image classification.",
    },
    {
        "id": "transfer-learning",
        "title": "Transfer learning",
        "category": "deep-learning",
        "text": "A pretrained model can provide useful features for a new task with a smaller labeled dataset.",
    },
    {
        "id": "transformers",
        "title": "Transformer attention",
        "category": "nlp",
        "text": "Self-attention lets each token combine information from other positions in the sequence.",
    },
    {
        "id": "local-llm",
        "title": "Local language models",
        "category": "nlp",
        "text": "Quantization can reduce memory usage and make some language models practical on local hardware.",
    },
    {
        "id": "embeddings",
        "title": "Text embeddings",
        "category": "nlp",
        "text": "An embedding model maps text to a dense vector so that related texts can be compared.",
    },
    {
        "id": "gpu",
        "title": "GPU computation",
        "category": "deep-learning",
        "text": "Moving tensors and models to a GPU can accelerate parallel numerical computation in PyTorch.",
    },
]

print("Number of documents:", len(documents))
print("First document:", documents[0])

Number of documents: 12
First document: {'id': 'python-environment', 'title': 'Python virtual environments', 'category': 'setup', 'text': 'Create a virtual environment to isolate the packages used by a Python project.'}

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><h3>پرسش‌های ارزیابی</h3><p>برای چهار <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Query</span>‏ زیر از قبل مشخص شده است کدام <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Document</span>‏ باید <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Relevant</span>‏ در نظر گرفته شود. بعداً از این داده برای محاسبه <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Precision@3</span>‏ و <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Recall@3</span>‏ استفاده می‌کنید.</p></div><div dir="ltr" style="direction:ltr; text-align:left; line-height:1.5; font-family:Arial, sans-serif; margin-top:4px; margin-bottom:12px;"><h4 style="margin-top:0;">Evaluation Queries</h4></div>

In [23]:
evaluation_queries = [
    {
        "query": "How do I make a separate Python environment?",
        "relevant_ids": {"python-environment"},
    },
    {
        "query": "Where do I submit the final project?",
        "relevant_ids": {"git-submission"},
    },
    {
        "query": "How can I reduce the memory needed by a local language model?",
        "relevant_ids": {"local-llm"},
    },
    {
        "query": "How can I test a model on unseen examples?",
        "relevant_ids": {"model-evaluation"},
    },
]

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><h1>بخش اول — اجرای یک مدل آماده</h1><p>مدرس می‌خواهد نشان دهد چگونه می‌توان یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Model</span>‏ آماده را در <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Hugging Face</span>‏ بررسی کرد و سپس آن را با <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Transformers</span>‏ اجرا کرد. قبل از اجرا باید مطمئن شویم <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Model</span>‏ برای <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Task</span>‏ موردنظر مناسب است.</p></div><div dir="ltr" style="direction:ltr; text-align:left; line-height:1.5; font-family:Arial, sans-serif; margin-top:4px; margin-bottom:12px;"><h2 style="margin-top:0;">Demo 1 — Pretrained NLP Model</h2></div>

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><h2>مأموریت ۱ — بررسی انتخاب مدل</h2><p>برای بخش اول به یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Model</span>‏ برای <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">English Sentiment Classification</span>‏ نیاز داریم. <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Model</span>‏ پیشنهادی در متغیر <code dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">SENTIMENT_MODEL_ID</code>‏ قرار دارد.</p><p><b>کار شما:</b> <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Metadata</span>‏ را دریافت کنید و <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Model Card</span>‏ را بررسی کنید.</p></div><div dir="ltr" style="direction:ltr; text-align:left; line-height:1.5; font-family:Arial, sans-serif; margin-top:4px; margin-bottom:12px;"><h3 style="margin-top:0;">Model Selection &amp; Model Card</h3></div>

In [24]:
info = model_info(SENTIMENT_MODEL_ID)

print("Model ID:", info.id)
print("Pipeline:", info.pipeline_tag)
print("Library:", info.library_name)
print("Downloads:", info.downloads)
print("Tags:", info.tags[:10])


from transformers import AutoConfig

config = AutoConfig.from_pretrained(SENTIMENT_MODEL_ID)

print("Model type:", config.model_type)
print("Architecture:", config.architectures)
print("Number of labels:", config.num_labels)
print("ID to label:", config.id2label)

Model ID: distilbert/distilbert-base-uncased-finetuned-sst-2-english
Pipeline: text-classification
Library: transformers
Downloads: 3489259
Tags: ['transformers', 'pytorch', 'tf', 'rust', 'onnx', 'safetensors', 'distilbert', 'text-classification', 'en', 'dataset:sst2']
Model type: distilbert
Architecture: ['DistilBertForSequenceClassification']
Number of labels: 2
ID to label: {0: 'NEGATIVE', 1: 'POSITIVE'}

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<table style="width:100%; border-collapse:collapse; margin:10px 0;"><tr><th dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;">مورد</th><th dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;">پاسخ شما</th></tr><tr><td dir="ltr" style="direction:ltr; text-align:left; border:1px solid #aaa; padding:7px;"><span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Model ID</span>‏</td><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;"></td></tr><tr><td dir="ltr" style="direction:ltr; text-align:left; border:1px solid #aaa; padding:7px;"><span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Task</span>‏</td><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;"></td></tr><tr><td dir="ltr" style="direction:ltr; text-align:left; border:1px solid #aaa; padding:7px;"><span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Language</span>‏</td><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;"></td></tr><tr><td dir="ltr" style="direction:ltr; text-align:left; border:1px solid #aaa; padding:7px;"><span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Pipeline Tag</span>‏</td><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;"></td></tr><tr><td dir="ltr" style="direction:ltr; text-align:left; border:1px solid #aaa; padding:7px;"><span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Library</span>‏</td><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;"></td></tr><tr><td dir="ltr" style="direction:ltr; text-align:left; border:1px solid #aaa; padding:7px;"><span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Expected Input</span>‏</td><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;"></td></tr><tr><td dir="ltr" style="direction:ltr; text-align:left; border:1px solid #aaa; padding:7px;"><span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Expected Output</span>‏</td><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;"></td></tr><tr><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;">یک نکته مهم یا <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Limitation</span>‏</td><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;"></td></tr></table>
<p><b>پاسخ دهید:</b></p>
<ol>
<li>آیا این <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Model</span>‏ از نظر <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Task</span>‏ و <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Language</span>‏ برای این <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Demo</span>‏ مناسب است؟ چرا؟</li>
<li>چرا تعداد زیاد <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Downloads</span>‏ به‌تنهایی دلیل کافی برای انتخاب یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Model</span>‏ نیست؟</li>
</ol>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><div style="border:1px dashed #999; border-radius:8px; padding:12px; margin:8px 0; min-height:60px;"><b>پاسخ شما:</b><br/><br/></div></div>

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><h2>مأموریت ۲ — اجرای اولین پیش‌بینی</h2><p>حالا که <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Model</span>‏ را بررسی کردیم، ساده‌ترین روش اجرا را با <code dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">pipeline()</code>‏ امتحان کنید. برای هر <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Text</span>‏ مقدار <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Label</span>‏ و <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Score</span>‏ را نمایش دهید.</p></div><div dir="ltr" style="direction:ltr; text-align:left; line-height:1.5; font-family:Arial, sans-serif; margin-top:4px; margin-bottom:12px;"><h3 style="margin-top:0;">Prediction with pipeline()</h3></div>

In [10]:
sentiment = pipeline(
    "sentiment-analysis",
    model=SENTIMENT_MODEL_ID,
)

texts = [
    "The explanation was clear and useful.",
    "The application crashes every time I open it.",
    "The course was interesting but difficult.",
]

results = sentiment(texts)

for text, result in zip(texts, results):
    print("Text:", text)
    print("Label:", result["label"])
    print("Score:", result["score"])
    print("-" * 60)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Text: The explanation was clear and useful.
Label: POSITIVE
Score: 0.9997910857200623
------------------------------------------------------------
Text: The application crashes every time I open it.
Label: NEGATIVE
Score: 0.9997283816337585
------------------------------------------------------------
Text: The course was interesting but difficult.
Label: NEGATIVE
Score: 0.8175790309906006
------------------------------------------------------------

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<p><b>پاسخ کوتاه:</b> در یک جمله توضیح دهید <code dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">pipeline()</code>‏ چه کاری را برای ما ساده کرده است.</p>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><div style="border:1px dashed #999; border-radius:8px; padding:12px; margin:8px 0; min-height:60px;"><b>پاسخ شما:</b><br/><br/></div></div>

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><h2>مأموریت ۳ — بررسی مراحل داخلی اجرا</h2><p>یکی از دانشجوهای <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Bootcamp</span>‏ می‌پرسد: «<span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Model</span>‏ که متن خام را مستقیماً پردازش نمی‌کند؛ پس بین <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Text</span>‏ و <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Label</span>‏ چه اتفاقی می‌افتد؟» این بار همان مسیر را مرحله‌به‌مرحله اجرا کنید.</p></div><div dir="ltr" style="direction:ltr; text-align:left; line-height:1.5; font-family:Arial, sans-serif; margin-top:4px; margin-bottom:12px;"><h3 style="margin-top:0;">Tokenizer → Logits → Probabilities → Label</h3></div>

<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<pre>
Raw Text
   ↓
Tokenizer
   ↓
input_ids + attention_mask
   ↓
Model
   ↓
Logits
   ↓
Softmax
   ↓
Probabilities
   ↓
Predicted Class
   ↓
Label
</pre>
</div>

In [11]:
tokenizer = AutoTokenizer.from_pretrained(
    SENTIMENT_MODEL_ID
)

model = AutoModelForSequenceClassification.from_pretrained(
    SENTIMENT_MODEL_ID
)

model.eval()

manual_texts = [
    "The lesson was useful.",
    "The result was disappointing.",
]

batch = tokenizer(
    manual_texts,
    padding=True,
    truncation=True,
    return_tensors="pt",
)

print("input_ids:")
print(batch["input_ids"])
print()

print("attention_mask:")
print(batch["attention_mask"])
print()

print("input_ids shape:", batch["input_ids"].shape)
print("attention_mask shape:", batch["attention_mask"].shape)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

input_ids:
tensor([[  101,  1996, 10800,  2001,  6179,  1012,   102],
        [  101,  1996,  2765,  2001, 15640,  1012,   102]])

attention_mask:
tensor([[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]])

input_ids shape: torch.Size([2, 7])
attention_mask shape: torch.Size([2, 7])

In [12]:
with torch.no_grad():
    outputs = model(**batch)

logits = outputs.logits
probabilities = torch.softmax(logits, dim=-1)
predicted_ids = probabilities.argmax(dim=-1)

print("Logits:")
print(logits)
print()

print("Probabilities:")
print(probabilities)
print()

for i, predicted_id in enumerate(predicted_ids):
    class_id = int(predicted_id)
    label = model.config.id2label[class_id]

    print("Text:", manual_texts[i])
    print("Predicted Class ID:", class_id)
    print("Final Label:", label)
    print("-" * 60)

Logits:
tensor([[-3.4947,  3.6668],
        [ 4.4451, -3.5993]])

Probabilities:
tensor([[7.7528e-04, 9.9922e-01],
        [9.9968e-01, 3.2079e-04]])

Text: The lesson was useful.
Predicted Class ID: 1
Final Label: POSITIVE
------------------------------------------------------------
Text: The result was disappointing.
Predicted Class ID: 0
Final Label: NEGATIVE
------------------------------------------------------------

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<table style="width:100%; border-collapse:collapse; margin:10px 0;"><tr><th dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;">مورد</th><th dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;">خروجی شما</th></tr><tr><td dir="ltr" style="direction:ltr; text-align:left; border:1px solid #aaa; padding:7px;"><span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Text</span>‏</td><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;"></td></tr><tr><td dir="ltr" style="direction:ltr; text-align:left; border:1px solid #aaa; padding:7px;"><span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Token IDs</span>‏</td><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;"></td></tr><tr><td dir="ltr" style="direction:ltr; text-align:left; border:1px solid #aaa; padding:7px;"><span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Logits</span>‏</td><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;"></td></tr><tr><td dir="ltr" style="direction:ltr; text-align:left; border:1px solid #aaa; padding:7px;"><span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Probabilities</span>‏</td><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;"></td></tr><tr><td dir="ltr" style="direction:ltr; text-align:left; border:1px solid #aaa; padding:7px;"><span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Predicted Class ID</span>‏</td><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;"></td></tr><tr><td dir="ltr" style="direction:ltr; text-align:left; border:1px solid #aaa; padding:7px;"><span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Final Label</span>‏</td><td dir="rtl" style="direction:rtl; text-align:right; border:1px solid #aaa; padding:7px;"></td></tr></table>
<p><b>پاسخ دهید:</b></p>
<ol>
<li>چرا <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Logit</span>‏ همان <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Probability</span>‏ نیست؟</li>
<li>چرا نام <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Class</span>‏ را از <code dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">model.config.id2label</code>‏ می‌خوانیم؟</li>
<li>حالا توضیح دهید <code dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">pipeline()</code>‏ چه مراحلی را برای ما انجام داده است.</li>
</ol>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><div style="border:1px dashed #999; border-radius:8px; padding:12px; margin:8px 0; min-height:60px;"><b>پاسخ شما:</b><br/><br/></div></div>

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><h2>مأموریت ۴ — بررسی ورودی‌های با طول متفاوت</h2><p>مدرس سه جمله با طول متفاوت وارد یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Batch</span>‏ می‌کند. با مشاهده خروجی واقعی مشخص کنید هر <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Sequence</span>‏ چگونه برای ورود به یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Tensor</span>‏ آماده شده است.</p></div><div dir="ltr" style="direction:ltr; text-align:left; line-height:1.5; font-family:Arial, sans-serif; margin-top:4px; margin-bottom:12px;"><h3 style="margin-top:0;">Padding &amp; Truncation</h3></div>

In [13]:
batch_texts = [
    "Short input.",
    "Another sentence in the same batch.",
    "A much longer sentence that contains several additional words.",
]

inputs = tokenizer(
    batch_texts,
    padding=True,
    truncation=True,
    max_length=10,
    return_tensors="pt",
)

print("input_ids:")
print(inputs["input_ids"])
print()

print("attention_mask:")
print(inputs["attention_mask"])
print()

print("shape:", inputs["input_ids"].shape)
print()

for i, row in enumerate(inputs["input_ids"]):
    print(f"Row {i}:")
    print(tokenizer.convert_ids_to_tokens(row))
    print()

input_ids:
tensor([[  101,  2460,  7953,  1012,   102,     0,     0,     0,     0,     0],
        [  101,  2178,  6251,  1999,  1996,  2168, 14108,  1012,   102,     0],
        [  101,  1037,  2172,  2936,  6251,  2008,  3397,  2195,  3176,   102]])

attention_mask:
tensor([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

shape: torch.Size([3, 10])

Row 0:
['[CLS]', 'short', 'input', '.', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']

Row 1:
['[CLS]', 'another', 'sentence', 'in', 'the', 'same', 'batch', '.', '[SEP]', '[PAD]']

Row 2:
['[CLS]', 'a', 'much', 'longer', 'sentence', 'that', 'contains', 'several', 'additional', '[SEP]']

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<p><b>با مشاهده خروجی پاسخ دهید:</b></p>
<ol>
<li>کدام <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Sequence</span>‏ شامل <code dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">[PAD]</code>‏ است؟</li>
<li>مقدار <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">attention_mask</span>‏ در محل مربوط به <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Padding</span>‏ چیست؟</li>
<li>چرا طول تمام <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Row</span>‏ در این <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Batch</span>‏ یکسان است؟</li>
<li>اگر یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Sequence</span>‏ <b>پس از <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Tokenization</span>‏</b> بیشتر از <code dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">max_length=10</code>‏ <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Token</span>‏ داشته باشد چه اتفاقی می‌افتد؟</li>
</ol>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><div style="border:1px dashed #999; border-radius:8px; padding:12px; margin:8px 0; min-height:60px;"><b>پاسخ شما:</b><br/><br/></div></div>


<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<h1>بخش دوم — بررسی <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Memory</span> و <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Quantization</span> روی سخت‌افزار محدود</h1>
<p>
بخش اول تمام شده است و <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Sentiment Model</span> را کنار می‌گذاریم.
در این بخش قرار نیست یک مدل بزرگ را واقعاً اجرا یا Download کنیم.
</p>
<p>
فقط فرض می‌کنیم یک Model دقیقاً <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">7,000,000,000 Parameters</span> دارد
و بررسی می‌کنیم Weightهای آن تقریباً چقدر Memory لازم دارند و Quantization چه اثری ایجاد می‌کند.
</p>
<p>
فرض سخت‌افزار:
<span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">8 GiB VRAM</span> و <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">32 GiB RAM</span>.
</p>
</div>
<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<h2>Demo 2 — Memory & Quantization</h2>
</div>


<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<h2>مأموریت ۵ — تخمین <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Weight Memory</span></h2>
<p>
مدل فرضی ما دقیقاً <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">7,000,000,000 Parameters</span> دارد.
در این سؤال فقط یک تخمین ساده و ایده‌آل از Memory مربوط به Weightها محاسبه می‌کنیم.
</p>
</div>
<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<h3>Idealized Raw Weight Memory</h3>
</div>

<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<p><b>Formula</b></p>
<p>
\[
\text{Idealized Raw Weight Memory}
\approx
\text{Parameters}
\times
\frac{\text{Bits per Parameter}}{8}
\]
</p>
</div>

In [14]:
def weight_memory_gib(parameters, bits):
    return parameters * bits / 8 / 1024**3

parameters = 7_000_000_000

representations = {
    "FP32": 32,
    "FP16": 16,
    "INT8": 8,
    "INT4": 4,
}

rows = []

for name, bits in representations.items():
    memory_gib = weight_memory_gib(parameters, bits)

    rows.append({
        "representation": name,
        "bits_per_parameter": bits,
        "idealized_raw_weight_memory_gib": round(memory_gib, 2),
        "below_8_gib": memory_gib < GPU_VRAM_GIB,
    })

memory_table = pd.DataFrame(rows)
memory_table

,representation,bits_per_parameter,idealized_raw_weight_memory_gib,below_8_gib
0,FP32,32,26.08,False
1,FP16,16,13.04,False
2,INT8,8,6.52,True
3,INT4,4,3.26,True

<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<table style="width:100%; border-collapse:collapse;">
<tr><th style="border:1px solid #aaa; padding:7px; text-align:left;">Representation</th><th style="border:1px solid #aaa; padding:7px; text-align:left;">Idealized Raw Weight Memory</th></tr>
<tr><td style="border:1px solid #aaa; padding:7px;">FP32</td><td style="border:1px solid #aaa; padding:7px;">≈ 26.08 GiB</td></tr>
<tr><td style="border:1px solid #aaa; padding:7px;">FP16</td><td style="border:1px solid #aaa; padding:7px;">≈ 13.04 GiB</td></tr>
<tr><td style="border:1px solid #aaa; padding:7px;">INT8</td><td style="border:1px solid #aaa; padding:7px;">≈ 6.52 GiB</td></tr>
<tr><td style="border:1px solid #aaa; padding:7px;">INT4</td><td style="border:1px solid #aaa; padding:7px;">≈ 3.26 GiB</td></tr>
</table>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<p><b>سؤال مهم:</b></p>
<p>
مدیر آزمایشگاه می‌گوید:
«برای <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">INT4</span>‏ مقدار تقریبی <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">3.26 GiB</span>‏ به‌دست آمده است و <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">GPU</span>‏ ما <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">8 GiB</span>‏ حافظه دارد؛
پس <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Model</span>‏ حتماً اجرا می‌شود.» آیا این نتیجه درست است؟
</p>
<p>
دلیل خود را بنویسید و حداقل سه مورد دیگر را نام ببرید که هنگام <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Inference</span>‏ می‌توانند <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Memory</span>‏ مصرف کنند.
</p>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><div style="border:1px dashed #999; border-radius:8px; padding:12px; margin:8px 0; min-height:60px;"><b>پاسخ شما:</b><br/><br/></div></div>

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><h2>مأموریت ۶ — بررسی اثر Quantization بر Weightها</h2><p>یکی از دانشجوها می‌پرسد: «آیا <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Quantization</span>‏ فقط همان مقدار <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Weight</span>‏ قبلی را بدون تغییر در فضای کمتری ذخیره می‌کند؟» برای بررسی، مثال آموزشی زیر را اجرا کنید.</p></div><div dir="ltr" style="direction:ltr; text-align:left; line-height:1.5; font-family:Arial, sans-serif; margin-top:4px; margin-bottom:12px;"><h3 style="margin-top:0;">Quantization</h3></div>

In [15]:
weights = torch.tensor([
    -0.80,
    -0.60,
     0.10,
     0.15,
     0.20,
     0.70,
])

scale = weights.abs().max() / 7

quantized = (
    torch.round(weights / scale)
    .clamp(-8, 7)
    .to(torch.int8)
)

reconstructed = quantized.float() * scale

absolute_error = (
    weights - reconstructed
).abs()

quantization_table = pd.DataFrame({
    "original": weights.tolist(),
    "quantized_code": quantized.tolist(),
    "reconstructed": reconstructed.tolist(),
    "absolute_error": absolute_error.tolist(),
})

quantization_table

   original  quantized_code  reconstructed  absolute_error
0     -0.80              -7      -0.800000        0.000000
1     -0.60              -5      -0.571429        0.028571
2      0.10               1       0.114286        0.014286
3      0.15               1       0.114286        0.035714
4      0.20               2       0.228571        0.028571
5      0.70               6       0.685714        0.014286

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<p><b>پاسخ دهید:</b></p>
<ol>
<li>کدام مقدار <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Weight</span>‏ کمترین <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Error</span>‏ را دارد؟</li>
<li>کدام مقدار <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Weight</span>‏ بیشترین <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Error</span>‏ را دارد؟</li>
<li>آیا تمام مقادیر <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Reconstructed Weight</span>‏ دقیقاً با مقدار <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Original</span>‏ برابر هستند؟</li>
<li>چرا <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Quantization</span>‏ می‌تواند خروجی <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Model</span>‏ را تغییر دهد؟</li>
</ol>
<p>
<b>نکته علمی:</b> این کد یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Tensor</span>‏ واقعی با قالب <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">packed INT4</span>‏ تولید نمی‌کند.
مقادیر فقط به محدوده <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">signed INT4</span>‏ محدود شده‌اند و در این مثال آموزشی داخل
<code dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">torch.int8</code>‏ نگهداری می‌شوند.
</p>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><div style="border:1px dashed #999; border-radius:8px; padding:12px; margin:8px 0; min-height:60px;"><b>پاسخ شما:</b><br/><br/></div></div>


<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<h2>مأموریت ۷ — از روی اعداد چه تصمیمی می‌توان گرفت؟</h2>
<p>
نتایج تخمین <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Raw Weight Memory</span> را دوباره در نظر بگیرید:
</p>
</div>

<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<table style="width:100%; border-collapse:collapse;">
<tr>
<th style="border:1px solid #aaa;padding:7px;text-align:left;">Representation</th>
<th style="border:1px solid #aaa;padding:7px;text-align:left;">Idealized Raw Weight Memory</th>
</tr>
<tr><td style="border:1px solid #aaa;padding:7px;">FP32</td><td style="border:1px solid #aaa;padding:7px;">26.08 GiB</td></tr>
<tr><td style="border:1px solid #aaa;padding:7px;">FP16</td><td style="border:1px solid #aaa;padding:7px;">13.04 GiB</td></tr>
<tr><td style="border:1px solid #aaa;padding:7px;">INT8</td><td style="border:1px solid #aaa;padding:7px;">6.52 GiB</td></tr>
<tr><td style="border:1px solid #aaa;padding:7px;">INT4</td><td style="border:1px solid #aaa;padding:7px;">3.26 GiB</td></tr>
</table>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<p><b>پاسخ دهید:</b></p>
<ol>
<li>فقط براساس <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Raw Weight Memory</span>، کدام Representationها از <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">8 GiB</span> کمتر هستند؟</li>
<li>چرا این نتیجه هنوز برای تضمین اجرای Model کافی نیست؟</li>
<li>چرا نمی‌توان گفت <b>bit-width کمتر یا numerical precision پایین‌تر</b> همیشه انتخاب بهتری است؟</li>
<li>برای مقایسه واقعی دو Configuration، علاوه بر Memory چه چیزهایی مانند Quality و Latency را باید اندازه‌گیری کنیم؟</li>
</ol>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><div style="border:1px dashed #999; border-radius:8px; padding:12px; margin:8px 0; min-height:60px;"><b>پاسخ شما:</b><br/><br/></div></div>


<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<h1>بخش سوم — جست‌وجو در محتوای دوره</h1>
<p>
بخش دوم تمام شده است.
از اینجا به بعد وارد Task جدیدی می‌شویم:
ساخت یک <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Search Engine</span> کوچک برای مجموعه‌ای شامل ۱۲ <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Document</span> آموزشی Bootcamp.
</p>
<p>
ممکن است <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Query</span> و <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Document</span> دقیقاً از یک Vocabulary استفاده نکنند؛
به همین دلیل از <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Sentence Embeddings</span> برای <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Semantic Retrieval</span> استفاده می‌کنیم.
</p>
</div>
<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<h2>Demo 3 — Semantic Search</h2>
</div>

<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<pre>
Document:
Students should upload the completed project
to the course GitHub repository before the deadline.

Query:
Where should I upload my final assignment?
</pre>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<p>
برای این بخش از <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">sentence-transformers/all-MiniLM-L6-v2</span>‏ استفاده می‌کنیم.
این <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Model</span>‏ برای هر <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Text</span>‏ یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Embedding</span>‏ تولید می‌کند تا بتوانیم <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Similarity</span>‏ را اندازه بگیریم.
</p>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><h2>مأموریت ۸ — بررسی شباهت معنایی</h2><p>قبل از ساخت <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Search Engine</span>‏، سه جمله را <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Encode</span>‏ کنید و <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Similarity Matrix</span>‏ را مشاهده کنید.</p></div><div dir="ltr" style="direction:ltr; text-align:left; line-height:1.5; font-family:Arial, sans-serif; margin-top:4px; margin-bottom:12px;"><h3 style="margin-top:0;">Sentence Embeddings &amp; Similarity</h3></div>

In [16]:
embedding_model = SentenceTransformer(
    EMBEDDING_MODEL_ID
)

sentences = [
    "How can I reset my password?",
    "I forgot my password. What should I do?",
    "The weather is sunny today.",
]

embeddings = embedding_model.encode(
    sentences,
    convert_to_tensor=True,
    normalize_embeddings=True,
)

similarity_matrix = embeddings @ embeddings.T

print("Embedding shape:", embeddings.shape)
print()
print("Similarity matrix:")
print(similarity_matrix)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding shape: torch.Size([3, 384])

Similarity matrix:
tensor([[ 1.0000,  0.8264, -0.0454],
        [ 0.8264,  1.0000, -0.0288],
        [-0.0454, -0.0288,  1.0000]])

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<p><b>از روی <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Matrix</span>‏ پاسخ دهید:</b></p>
<ol>
<li>چرا <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Matrix</span>‏ دارای <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Shape</span>‏ برابر <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">3 × 3</span>‏ است؟</li>
<li>چرا مقدارهای قطر اصلی تقریباً 1 هستند؟</li>
<li>جمله اول به جمله دوم نزدیک‌تر است یا جمله سوم؟</li>
<li>آیا نتیجه با معنی جمله‌ها سازگار است؟</li>
</ol>
</div>

<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<p><b>Short mathematical question</b></p>
<p>If normalized vectors satisfy:</p>
<p>\[
\|a\|=\|b\|=1
\]</p>
<p>and</p>
<p>\[
\cos(a,b)=\frac{a^Tb}{\|a\|\|b\|}
\]</p>
<p>explain why:</p>
<p>\[
a^Tb=\cos(a,b)
\]</p>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><div style="border:1px dashed #999; border-radius:8px; padding:12px; margin:8px 0; min-height:60px;"><b>پاسخ شما:</b><br/><br/></div></div>

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><h2>مأموریت ۹ — تبدیل مجموعه اسناد به بردار</h2><p>حالا به‌جای سه جمله، مجموعه ۱۲ موردی <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Document</span>‏ را با همان <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Embedding Model</span>‏ پردازش و <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Encode</span>‏ کنید.</p></div><div dir="ltr" style="direction:ltr; text-align:left; line-height:1.5; font-family:Arial, sans-serif; margin-top:4px; margin-bottom:12px;"><h3 style="margin-top:0;">Knowledge Base → Document Embeddings</h3></div>

In [17]:
texts = [
    document["text"]
    for document in documents
]

document_embeddings = embedding_model.encode(
    texts,
    convert_to_tensor=True,
    normalize_embeddings=True,
)

print("document_embeddings shape:", document_embeddings.shape)
print("one document vector shape:", document_embeddings[0].shape)

document_embeddings shape: torch.Size([12, 384])
one document vector shape: torch.Size([384])

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<p>
انتظار داریم <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Shape</span>‏ کلی برابر <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">[12, 384]</span>‏ و <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Shape</span>‏ مربوط به یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Document</span>‏ برابر <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">[384]</span>‏ باشد.
</p>
<p><b>پاسخ دهید:</b></p>
<ol>
<li>عدد 12 چه چیزی را نشان می‌دهد؟</li>
<li>عدد 384 چه چیزی را نشان می‌دهد؟</li>
</ol>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><div style="border:1px dashed #999; border-radius:8px; padding:12px; margin:8px 0; min-height:60px;"><b>پاسخ شما:</b><br/><br/></div></div>

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><h2>مأموریت ۱۰ — اجرای اولین جست‌وجوی معنایی</h2><p>یکی از دانشجوها <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Query</span>‏ زیر را وارد می‌کند:</p></div><div dir="ltr" style="direction:ltr; text-align:left; line-height:1.5; font-family:Arial, sans-serif; margin-top:4px; margin-bottom:12px;"><h3 style="margin-top:0;">Semantic Search &amp; Top-K Retrieval</h3></div>

<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;"><p><code>Where should I upload my final assignment?</code></p></div>


<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<p>
یک تابع <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Search</span>‏ بنویسید. ابتدا <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Query</span>‏ را با همان <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Embedding Model</span>‏ و همان روش <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Normalization</span>‏ به‌صورت <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Encode</span>‏ تبدیل کنید.
سپس <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Similarity</span>‏ را برای تمام ۱۲ <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Document</span>‏ محاسبه کنید و در پایان <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Top-K</span>‏ را برگردانید.
</p>
</div>

In [18]:
def semantic_search(
    query,
    documents,
    document_embeddings,
    embedding_model,
    top_k=3,
):
    # TODO 1: Encode the query with the same model and normalization.
    query_embedding = ...

    # TODO 2: Compute similarity scores.
    scores = ...

    # TODO 3: Select the top-k results.
    top_scores, top_indices = ...

    # TODO 4: Return results together with their metadata.
    results = []

    for score, index in zip(top_scores, top_indices):
        index = int(index.item())

        result = documents[index].copy()
        result["score"] = float(score)
        results.append(result)

    return results

In [19]:
query = "Where should I upload my final assignment?"

# Run this cell after completing semantic_search().
results = semantic_search(
    query,
    documents,
    document_embeddings,
    embedding_model,
    top_k=3,
)

print("Query:", query)

for rank, result in enumerate(results, start=1):
    print(
        rank,
        "|",
        result["id"],
        "|",
        result["title"],
        "|",
        round(result["score"], 3),
    )

TypeError: cannot unpack non-iterable ellipsis object

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<p><b>پاسخ دهید:</b></p>
<ol>
<li>آیا <code dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">git-submission</code>‏ در <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Top-3</span>‏ قرار گرفته است؟</li>
<li>آیا <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Query</span>‏ و <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Document</span>‏ اول دقیقاً از همان کلمات استفاده کرده‌اند؟</li>
</ol>
<p>
<b>نکته:</b> خروجی <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Semantic Search</span>‏ یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Ranked List</span>‏ است، نه یک پاسخ تضمین‌شده.
</p>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><div style="border:1px dashed #999; border-radius:8px; padding:12px; margin:8px 0; min-height:60px;"><b>پاسخ شما:</b><br/><br/></div></div>

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><h2>مأموریت ۱۱ — مقایسه دو روش جست‌وجو</h2><p>مدرس می‌خواهد یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Semantic Method</span>‏ را با یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Lexical Baseline</span>‏ مقایسه کند. برای همان مجموعه ۱۲ موردی <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Document</span>‏ یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">TF-IDF Index</span>‏ بسازید.</p></div><div dir="ltr" style="direction:ltr; text-align:left; line-height:1.5; font-family:Arial, sans-serif; margin-top:4px; margin-bottom:12px;"><h3 style="margin-top:0;">Semantic Search vs. TF-IDF</h3></div>

In [ ]:
tfidf_vectorizer = TfidfVectorizer()

tfidf_documents = tfidf_vectorizer.fit_transform(
    texts
)

def tfidf_search(
    query,
    documents,
    vectorizer,
    document_matrix,
    top_k=3,
):
    # TODO 1: Transform the query into a TF-IDF vector.
    query_vector = ...

    # TODO 2: Compute cosine similarity against all documents.
    scores = ...

    # TODO 3: Select the top-k document indices.
    top_indices = ...

    # TODO 4: Return the results.
    return [
        {
            "document": documents[index],
            "score": float(scores[index]),
        }
        for index in top_indices
    ]

In [ ]:
comparison_query = "Where can I send my completed project?"

# Run this cell after completing both search functions.
semantic_results = semantic_search(
    comparison_query,
    documents,
    document_embeddings,
    embedding_model,
    top_k=3,
)

tfidf_results = tfidf_search(
    comparison_query,
    documents,
    tfidf_vectorizer,
    tfidf_documents,
    top_k=3,
)

print("SEMANTIC SEARCH")
for rank, item in enumerate(semantic_results, start=1):
    print(rank, "|", item["id"], "|", round(item["score"], 3))

print()
print("TF-IDF SEARCH")
for rank, item in enumerate(tfidf_results, start=1):
    print(
        rank,
        "|",
        item["document"]["id"],
        "|",
        round(item["score"], 3),
    )

<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<table style="width:100%; border-collapse:collapse;">
<tr>
<th style="border:1px solid #aaa; padding:7px; text-align:left;">Rank</th>
<th style="border:1px solid #aaa; padding:7px; text-align:left;">Semantic Search</th>
<th style="border:1px solid #aaa; padding:7px; text-align:left;">TF-IDF</th>
</tr>
<tr><td style="border:1px solid #aaa; padding:7px;">1</td><td style="border:1px solid #aaa; padding:7px;"></td><td style="border:1px solid #aaa; padding:7px;"></td></tr>
<tr><td style="border:1px solid #aaa; padding:7px;">2</td><td style="border:1px solid #aaa; padding:7px;"></td><td style="border:1px solid #aaa; padding:7px;"></td></tr>
<tr><td style="border:1px solid #aaa; padding:7px;">3</td><td style="border:1px solid #aaa; padding:7px;"></td><td style="border:1px solid #aaa; padding:7px;"></td></tr>
</table>
</div>


<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<p><b>پاسخ دهید:</b></p>
<ol>
<li>روش <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">TF-IDF</span>‏ بیشتر بر چه نوع <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Signal</span>‏ تکیه می‌کند؟</li>
<li>روش <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Semantic Search</span>‏ بیشتر بر چه نوع <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Signal</span>‏ تکیه می‌کند؟</li>
<li>آیا می‌توان فقط با همین یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Query</span>‏ نتیجه گرفت یکی از این دو روش همیشه بهتر است؟ چرا؟</li>
</ol>
<p>
<b>نکته:</b> مقدار عددی <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Score</span>‏ در دو روش را مستقیماً با هم مقایسه نکنید.
به‌جای آن، <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Ranking</span>‏ و میزان مرتبط بودن نتیجه‌ها را مقایسه کنید.
</p>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><div style="border:1px dashed #999; border-radius:8px; padding:12px; margin:8px 0; min-height:60px;"><b>پاسخ شما:</b><br/><br/></div></div>

<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><h2>مأموریت ۱۲ — ارزیابی سیستم جست‌وجو</h2><p>اجرای <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Search</span>‏ روی یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Query</span>‏ برای ارزیابی سیستم کافی نیست. برای چهار <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Query</span>‏ تعریف‌شده در ابتدای <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Notebook</span>‏، <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Top-3</span>‏ را پیدا کنید و <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Precision@3</span>‏ و <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Recall@3</span>‏ را محاسبه کنید.</p></div><div dir="ltr" style="direction:ltr; text-align:left; line-height:1.5; font-family:Arial, sans-serif; margin-top:4px; margin-bottom:12px;"><h3 style="margin-top:0;">Precision@3 &amp; Recall@3</h3></div>

<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<p><b>Metrics</b></p>
<p>
\[
Precision@3=
\frac{\text{Relevant Results in Top-3}}{3}
\]
</p>
<p>
\[
Recall@3=
\frac{\text{Relevant Results in Top-3}}
{\text{Total Relevant Documents}}
\]
</p>
</div>

In [ ]:
def precision_at_k(result_ids, relevant_ids, k):
    # TODO
    ...

def recall_at_k(result_ids, relevant_ids, k):
    # TODO
    ...


evaluation_rows = []

for item in evaluation_queries:
    # TODO: Run semantic_search() with top_k=3.
    search_results = ...

    # TODO: Extract retrieved document IDs.
    retrieved_ids = ...

    # TODO: Compute Precision@3 and Recall@3.
    p3 = ...
    r3 = ...

    evaluation_rows.append({
        "query": item["query"],
        "relevant_ids": sorted(item["relevant_ids"]),
        "retrieved_ids": retrieved_ids,
        "precision_at_3": p3,
        "recall_at_3": r3,
    })

evaluation_table = pd.DataFrame(evaluation_rows)
evaluation_table

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<p><b>پاسخ دهید:</b></p>
<ol>
<li>
اگر فقط یک <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Relevant Document</span>‏ برای <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Query</span>‏ وجود داشته باشد و همان <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Document</span>‏ در <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Top-3</span>‏ پیدا شود،
چرا <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Recall@3 = 1</span>‏ ولی <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Precision@3 = 1/3</span>‏ می‌شود؟
</li>
<li>
آیا نتیجه این چهار <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Query</span>‏ کافی است تا بگوییم <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Search Engine</span>‏ برای <span dir="ltr" lang="en" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap; text-align:left;">Production</span>‏ آماده است؟
دلیل خود را در یک یا دو جمله بنویسید.
</li>
</ol>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><div style="border:1px dashed #999; border-radius:8px; padding:12px; margin:8px 0; min-height:60px;"><b>پاسخ شما:</b><br/><br/></div></div>


<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<h1>جمع‌بندی نهایی</h1>
<p>
این تمرین سه نوع مسئله متفاوت را بررسی کرد:
<span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Classification</span>، تحلیل <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Memory / Quantization</span> و <span dir="ltr" style="direction:ltr; unicode-bidi:isolate; display:inline-block; white-space:nowrap;">Retrieval</span>.
</p>
</div>
<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<h2>Bootcamp Summary</h2>
</div>


<div dir="ltr" style="direction:ltr; text-align:left; unicode-bidi:isolate; line-height:1.8; font-family:Arial, sans-serif; font-size:15px;">
<table style="width:100%; border-collapse:collapse;">
<tr>
<th style="border:1px solid #aaa; padding:7px; text-align:left;">Part</th>
<th style="border:1px solid #aaa; padding:7px; text-align:left;">Main Result</th>
</tr>
<tr><td style="border:1px solid #aaa; padding:7px;">Classification</td><td style="border:1px solid #aaa; padding:7px;">Label / probabilities</td></tr>
<tr><td style="border:1px solid #aaa; padding:7px;">Memory & Quantization analysis</td><td style="border:1px solid #aaa; padding:7px;">Memory estimates / reconstruction error</td></tr>
<tr><td style="border:1px solid #aaa; padding:7px;">Embedding & Retrieval</td><td style="border:1px solid #aaa; padding:7px;">Vectors / ranked documents</td></tr>
</table>
</div>


<div dir="rtl" style="direction:rtl; text-align:right; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;">
<p><b>پرسش پایانی:</b></p>
<p>
در یک پاراگراف کوتاه توضیح دهید در این تمرین چه تفاوتی میان
<span dir="ltr" style="unicode-bidi:isolate;">Classification</span>،
<span dir="ltr" style="unicode-bidi:isolate;">Memory / Quantization Analysis</span>
و
<span dir="ltr" style="unicode-bidi:isolate;">Retrieval</span>
وجود داشت.
</p>
</div>

<div dir="rtl" style="direction:rtl; text-align:right; unicode-bidi:isolate; line-height:2; font-family:Tahoma, Arial, sans-serif; font-size:16px;"><div style="border:1px dashed #999; border-radius:8px; padding:12px; margin:8px 0; min-height:60px;"><b>پاسخ شما:</b><br/><br/></div></div>